In [1]:
import pandas as pd

In [2]:
df2021 = pd.read_csv("accident2021.csv", encoding="utf-8-sig")
df2022 = pd.read_csv("accident2022.csv", encoding="utf-8-sig")
df2023 = pd.read_csv("accident2023.csv", encoding="utf-8-sig")
df2024 = pd.read_csv("accident2024.csv", encoding="utf-8-sig")
df2025 = pd.read_csv("accident2025.csv", encoding="utf-8-sig")

In [3]:
files = {
    "2021": df2021,
    "2022": df2022,
    "2023": df2023,
    "2024": df2024,
    "2025": df2025
}

for year, df in files.items():
    print(f"\n===== {year} =====")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

===== 2021 =====
Rows: 20062
Columns: 38

===== 2022 =====
Rows: 20566
Columns: 38

===== 2023 =====
Rows: 23841
Columns: 38

===== 2024 =====
Rows: 23952
Columns: 38

===== 2025 =====
Rows: 23715
Columns: 38

In [4]:
print(df2021.columns.equals(df2022.columns))
print(df2022.columns.equals(df2023.columns))
print(df2023.columns.equals(df2024.columns))
print(df2024.columns.equals(df2025.columns))
print(df2025.columns.equals(df2025.columns))

True
True
True
True
True

In [5]:
accident_all = pd.concat(
    [df2021, df2022, df2023, df2024, df2025],
    ignore_index=True
)

In [6]:
print("จำนวนแถว:", accident_all.shape[0])
print("จำนวนคอลัมน์:", accident_all.shape[1])

จำนวนแถว: 112136
จำนวนคอลัมน์: 38

In [39]:
accident_all.head(5)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,ACC_CODE,หน่วยงาน,สายทางหน่วยงาน,รหัสสายทาง,สายทาง,...,รถอีแต๋น,รถอื่นๆ,คนเดินเท้า,ผู้เสียชีวิต,ผู้บาดเจ็บสาหัส,ผู้บาดเจ็บเล็กน้อย,รวมจำนวนผู้บาดเจ็บ,เดือน,วันในสัปดาห์,ชั่วโมง
0,2021,2021-01-01,0:00,6/2/2021,9:04,4172437,กรมทางหลวง,ทางหลวง,2044,ร้อยเอ็ด - หนองดง,...,0,0,0,0,0,2,2,1,ศุกร์,0.0
1,2021,2021-01-01,0:02,1/2/2021,6:31,2918300,กรมทางหลวงชนบท,ทางหลวงชนบท,สน.3054,แยกทางหลวงหมายเลข 223 (กม.ที่ 11+000) - บ้านด่...,...,0,0,0,0,0,1,1,1,ศุกร์,0.0
2,2021,2021-01-01,0:05,1/2/2021,6:28,2918203,กรมทางหลวงชนบท,ทางหลวงชนบท,นพ.3015,แยกทางหลวงหมายเลข 212 (กม.ที่ 70+535) - บ้านบา...,...,0,0,0,0,0,1,1,1,ศุกร์,0.0
3,2021,2021-01-01,0:05,1/1/2021,10:16,3812049,กรมทางหลวง,ทางหลวง,4169,ทางรอบเกาะสมุย,...,0,0,0,0,0,5,5,1,ศุกร์,0.0
4,2021,2021-01-01,0:05,1/4/2021,9:40,3812534,กรมทางหลวง,ทางหลวง,1143,น้ำคลาด - ปางหมิ่น,...,0,0,0,1,2,0,2,1,ศุกร์,0.0

In [8]:
accident_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112136 entries, 0 to 112135
Data columns (total 38 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ปีที่เกิดเหตุ         112136 non-null  int64
 1   วันที่เกิดเหตุ        112136 non-null  object
 2   เวลา                  112136 non-null  object
 3   วันที่รายงาน          112132 non-null  object
 4   เวลาที่รายงาน         112128 non-null  object
 5   ACC_CODE              112136 non-null  int64
 6   หน่วยงาน              112136 non-null  object
 7   สายทางหน่วยงาน        112136 non-null  object
 8   รหัสสายทาง            112124 non-null  object
 9   สายทาง                89967 non-null   object
 10  KM                    111219 non-null  float64
 11  จังหวัด               110184 non-null  object
 12  รถคันที่1             110419 non-null  object
 13  บริเวณที่เกิดเหตุ     102795 non-null  object
 14  มูลเหตุสันนิษฐาน      109966 non-null  object
 15  ลักษณะการเกิดเหตุ     105934 non-null  object
 16  สภาพอากาศ             111392 non-null  object
 17  LATITUDE              111415 non-null  float64
 18  LONGITUDE             111415 non-null  float64
 19  รถที่เกิดเหตุ         112136 non-null  int64
 20  รถและคนที่เกิดเหตุ    112136 non-null  int64
 21  รถจักรยานยนต์         112136 non-null  int64
 22  รถสามล้อเครื่อง       112136 non-null  int64
 23  รถยนต์นั่งส่วนบุคคล   112136 non-null  int64
 24  รถตู้                 112136 non-null  int64
 25  รถปิคอัพโดยสาร        112136 non-null  int64
 26  รถโดยสารมากกว่า4ล้อ   112136 non-null  int64
 27  รถปิคอัพบรรทุก4ล้อ    112136 non-null  int64
 28  รถบรรทุก6ล้อ          112136 non-null  int64
 29  รถบรรทุกไม่เกิน10ล้อ  112136 non-null  int64
 30  รถบรรทุกมากกว่า10ล้อ  112136 non-null  int64
 31  รถอีแต๋น              112136 non-null  int64
 32  รถอื่นๆ               112136 non-null  int64
 33  คนเดินเท้า            112136 non-null  int64
 34  ผู้เสียชีวิต          112136 non-null  int64
 35  ผู้บาดเจ็บสาหัส       112136 non-null  int64
 36  ผู้บาดเจ็บเล็กน้อย    112136 non-null  int64
 37  รวมจำนวนผู้บาดเจ็บ    112136 non-null  int64
dtypes: float64(3), int64(21), object(14)
memory usage: 32.5+ MB

In [9]:
accident_all.to_csv(
    "accident_all.csv",
    index=False,
    encoding="utf-8-sig"
)

In [10]:
accident_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112136 entries, 0 to 112135
Data columns (total 38 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ปีที่เกิดเหตุ         112136 non-null  int64
 1   วันที่เกิดเหตุ        112136 non-null  object
 2   เวลา                  112136 non-null  object
 3   วันที่รายงาน          112132 non-null  object
 4   เวลาที่รายงาน         112128 non-null  object
 5   ACC_CODE              112136 non-null  int64
 6   หน่วยงาน              112136 non-null  object
 7   สายทางหน่วยงาน        112136 non-null  object
 8   รหัสสายทาง            112124 non-null  object
 9   สายทาง                89967 non-null   object
 10  KM                    111219 non-null  float64
 11  จังหวัด               110184 non-null  object
 12  รถคันที่1             110419 non-null  object
 13  บริเวณที่เกิดเหตุ     102795 non-null  object
 14  มูลเหตุสันนิษฐาน      109966 non-null  object
 15  ลักษณะการเกิดเหตุ     105934 non-null  object
 16  สภาพอากาศ             111392 non-null  object
 17  LATITUDE              111415 non-null  float64
 18  LONGITUDE             111415 non-null  float64
 19  รถที่เกิดเหตุ         112136 non-null  int64
 20  รถและคนที่เกิดเหตุ    112136 non-null  int64
 21  รถจักรยานยนต์         112136 non-null  int64
 22  รถสามล้อเครื่อง       112136 non-null  int64
 23  รถยนต์นั่งส่วนบุคคล   112136 non-null  int64
 24  รถตู้                 112136 non-null  int64
 25  รถปิคอัพโดยสาร        112136 non-null  int64
 26  รถโดยสารมากกว่า4ล้อ   112136 non-null  int64
 27  รถปิคอัพบรรทุก4ล้อ    112136 non-null  int64
 28  รถบรรทุก6ล้อ          112136 non-null  int64
 29  รถบรรทุกไม่เกิน10ล้อ  112136 non-null  int64
 30  รถบรรทุกมากกว่า10ล้อ  112136 non-null  int64
 31  รถอีแต๋น              112136 non-null  int64
 32  รถอื่นๆ               112136 non-null  int64
 33  คนเดินเท้า            112136 non-null  int64
 34  ผู้เสียชีวิต          112136 non-null  int64
 35  ผู้บาดเจ็บสาหัส       112136 non-null  int64
 36  ผู้บาดเจ็บเล็กน้อย    112136 non-null  int64
 37  รวมจำนวนผู้บาดเจ็บ    112136 non-null  int64
dtypes: float64(3), int64(21), object(14)
memory usage: 32.5+ MB

In [11]:
accident_all.isnull().sum()

ปีที่เกิดเหตุ               0
วันที่เกิดเหตุ              0
เวลา                        0
วันที่รายงาน                4
เวลาที่รายงาน               8
ACC_CODE                    0
หน่วยงาน                    0
สายทางหน่วยงาน              0
รหัสสายทาง                 12
สายทาง                  22169
KM                        917
จังหวัด                  1952
รถคันที่1                1717
บริเวณที่เกิดเหตุ        9341
มูลเหตุสันนิษฐาน         2170
ลักษณะการเกิดเหตุ        6202
สภาพอากาศ                 744
LATITUDE                  721
LONGITUDE                 721
รถที่เกิดเหตุ               0
รถและคนที่เกิดเหตุ          0
รถจักรยานยนต์               0
รถสามล้อเครื่อง             0
รถยนต์นั่งส่วนบุคคล         0
รถตู้                       0
รถปิคอัพโดยสาร              0
รถโดยสารมากกว่า4ล้อ         0
รถปิคอัพบรรทุก4ล้อ          0
รถบรรทุก6ล้อ                0
รถบรรทุกไม่เกิน10ล้อ        0
รถบรรทุกมากกว่า10ล้อ        0
รถอีแต๋น                    0
รถอื่นๆ                     0
คนเดินเท้า                  0
ผู้เสียชีวิต                0
ผู้บาดเจ็บสาหัส             0
ผู้บาดเจ็บเล็กน้อย          0
รวมจำนวนผู้บาดเจ็บ          0
dtype: int64

In [12]:
print("Duplicate:", accident_all.duplicated().sum())

Duplicate: 61

In [13]:
for col in accident_all.columns:
    print(col)

ปีที่เกิดเหตุ
วันที่เกิดเหตุ
เวลา
วันที่รายงาน
เวลาที่รายงาน
ACC_CODE
หน่วยงาน
สายทางหน่วยงาน
รหัสสายทาง
สายทาง
KM
จังหวัด
รถคันที่1
บริเวณที่เกิดเหตุ
มูลเหตุสันนิษฐาน
ลักษณะการเกิดเหตุ
สภาพอากาศ
LATITUDE
LONGITUDE
รถที่เกิดเหตุ
รถและคนที่เกิดเหตุ
รถจักรยานยนต์
รถสามล้อเครื่อง
รถยนต์นั่งส่วนบุคคล
รถตู้
รถปิคอัพโดยสาร
รถโดยสารมากกว่า4ล้อ
รถปิคอัพบรรทุก4ล้อ
รถบรรทุก6ล้อ
รถบรรทุกไม่เกิน10ล้อ
รถบรรทุกมากกว่า10ล้อ
รถอีแต๋น
รถอื่นๆ
คนเดินเท้า
ผู้เสียชีวิต
ผู้บาดเจ็บสาหัส
ผู้บาดเจ็บเล็กน้อย
รวมจำนวนผู้บาดเจ็บ

In [14]:
accident_all["จังหวัด"].value_counts(dropna=False)

จังหวัด
กรุงเทพมหานคร    11372
ชลบุรี            6289
นครราชสีมา        4882
เชียงใหม่         3758
สุพรรณบุรี        3595
                 ...
สตูล               366
พิจิตร             299
หนองคาย            293
อำนาจเจริญ         269
ระนอง              257
Name: count, Length: 78, dtype: int64

In [15]:
sorted(accident_all["จังหวัด"].dropna().unique())

['กระบี่',
 'กรุงเทพมหานคร',
 'กาญจนบุรี',
 'กาฬสินธุ์',
 'กำแพงเพชร',
 'ขอนแก่น',
 'จันทบุรี',
 'ฉะเชิงเทรา',
 'ชลบุรี',
 'ชัยนาท',
 'ชัยภูมิ',
 'ชุมพร',
 'ตรัง',
 'ตราด',
 'ตาก',
 'นครนายก',
 'นครปฐม',
 'นครพนม',
 'นครราชสีมา',
 'นครศรีธรรมราช',
 'นครสวรรค์',
 'นนทบุรี',
 'นราธิวาส',
 'น่าน',
 'บึงกาฬ',
 'บุรีรัมย์',
 'ปทุมธานี',
 'ประจวบคีรีขันธ์',
 'ปราจีนบุรี',
 'ปัตตานี',
 'พะเยา',
 'พังงา',
 'พัทลุง',
 'พิจิตร',
 'พิษณุโลก',
 'ภูเก็ต',
 'มหาสารคาม',
 'มุกดาหาร',
 'ยะลา',
 'ยโสธร',
 'ระนอง',
 'ระยอง',
 'ราชบุรี',
 'ร้อยเอ็ด',
 'ลพบุรี',
 'ลำปาง',
 'ลำพูน',
 'ศรีสะเกษ',
 'สกลนคร',
 'สงขลา',
 'สตูล',
 'สมุทรปราการ',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สระบุรี',
 'สระแก้ว',
 'สิงห์บุรี',
 'สุพรรณบุรี',
 'สุราษฎร์ธานี',
 'สุรินทร์',
 'สุโขทัย',
 'หนองคาย',
 'หนองบัวลำภู',
 'อยุธยา',
 'อำนาจเจริญ',
 'อุดรธานี',
 'อุตรดิตถ์',
 'อุทัยธานี',
 'อุบลราชธานี',
 'อ่างทอง',
 'เชียงราย',
 'เชียงใหม่',
 'เพชรบุรี',
 'เพชรบูรณ์',
 'เลย',
 'แพร่',
 'แม่ฮ่องสอน']

In [17]:
accident_all["สภาพอากาศ"].value_counts(dropna=False)

สภาพอากาศ
แจ่มใส                           97031
ฝนตก                             13537
NaN                                744
มีหมอก/ควัน/ฝุ่น                   392
มืดครึ้ม                           297
อื่นๆ                               79
ภัยธรรมชาติ เช่น พายุ น้ำท่วม       56
Name: count, dtype: int64

In [18]:
accident_all["มูลเหตุสันนิษฐาน"].value_counts(dropna=False)

มูลเหตุสันนิษฐาน
ขับรถเร็วเกินอัตรากำหนด         64494
ขับรถเร็วเกินอัตราที่กำหนด      14636
หลับใน                           7712
คน/รถ/สัตว์ตัดหน้ากระชั้นชิด     6680
NaN                              2170
                                ...
ระบบไฟขัดข้องในห้องเครื่อง          1
ขับขี่ย้อนศร                        1
ระบบบังขับเลี้ยวชำรุด               1
ฝาตู้เก็บของด้านข้างเปิด            1
เบรคกะทันหัน                        1
Name: count, Length: 117, dtype: int64

In [20]:
accident_all["มูลเหตุสันนิษฐาน"] = accident_all["มูลเหตุสันนิษฐาน"].replace({

    "ขับขี่ย้อนศร": "ขับรถย้อนศร",

    "ขับชิดซ้ายมากเกินไป": "ขับรถชิดซ้ายมากเกินไป",

    "ขับรถกระชั้นชิด": "ขับรถตามกระชั้นชิด",

    "ฝ่าฝืนสัญญาณไฟ / เครื่องหมายจราจร": "ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร",

    "ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมทางแยก": "ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมแยก",

    "มึนเมาจากแอลกอฮอล์": "เมาสุรา",

    "รถเสียไม่แสดงเครื่องหมาย/สัญญาณตามที่กำหนด":
        "รถเสียไม่แสดงเครื่องหมายหรือสัญญาณไฟที่กำหนด",

    "ระบบไฟฟ้ขัดข้อง": "ระบบไฟฟ้าขัดข้อง",
    "ระบบไฟฟ้าของยานพาหนะขัดข้อง": "ระบบไฟฟ้าขัดข้อง",

    "อาการป่วย หรือการไร้ความสามารถทางประสาทหรือร่างกาย":
        "อาการป่วยหรือการไร้ความสามารถทางประสาทหรือร่างกาย",

    "ใช้โทรศัพท์เคลื่อนที่ขณะขับรถ": "ใช้โทรศัพท์ขณะขับรถ",

    "ไม่ให้สัญญาณชะลอ / เลี้ยว": "ไม่ให้สัญญาณชะลอ/เลี้ยว",

    "ไม่ให้สัญญาณเข้าจอด หรือออกจากที่จอด":
        "ไม่ให้สัญญาณเข้าจอด/ออกจากที่จอด",

    "ไม่คุ้นเคยกับการขับขี่ด้านซ้าย เช่น กรณีชาวต่างชาติ":
        "ไม่คุ้นเคยกับการขับขี่ด้านซ้าย",

    "เบรคกะทันหัน": "เบรกกะทันหัน",
    
    "เบรคกระทันหัน": "เบรกกะทันหัน",
    
    "เบครกระทันหัน": "เบรกกะทันหัน",

    "ถนนลื่น (เนื่องจากสภาพอากาศ)": "ถนนลื่น",

    "มีสิ่งรบกวนภายในรถ เช่น มีเด็ก มีสัตว์ภายในรถ":
        "มีสิ่งรบกวนภายในรถ",

    "แสงสว่างไม่เพียงพอหรือทัศนวิสัยกลางคืนไม่ดี":
        "แสงสว่างไม่เพียงพอ",

    "เข้าผิดช่องทางผิด": "เข้าผิดช่อง",

    "ไม่คุ้นชินกับยานพาหนะ เช่น กรณีเช่ารถ":
        "ไม่คุ้นเคยเส้นทาง/ขับรถไม่ชำนาญ"
})

In [21]:
accident_all["มูลเหตุสันนิษฐาน"] = accident_all["มูลเหตุสันนิษฐาน"].replace({
  
     "อุปกรณ์ยานพาหนะบกพร่อง (ระบุ)": "อุปกรณ์ยานพาหนะบกพร่อง"
})

In [22]:
for value in sorted(accident_all["มูลเหตุสันนิษฐาน"].dropna().unique()):
    print(value)

การกระทำที่สุ่มเสี่ยงบนถนน
การซ่อม/สร้างบนสายทาง
กำลังเครื่องยนต์ไม่เพียงพอ
ขับขี่ช้าเกินเนื่องจากลักษณะของยานพาหนะ (เช่น แทรคเตอร์)
ขับชิดขอบทางขวามากเกินไป
ขับรถคร่อมเส้นแบ่งทิศทาง
ขับรถชิดขวามากไป
ขับรถชิดซ้ายมากเกินไป
ขับรถช้าลง
ขับรถตามกระชั้นชิด
ขับรถผิดช่องทาง
ขับรถย้อนศร
ขับรถเร็วเกินอัตรากำหนด
ขับรถเร็วเกินอัตราที่กำหนด
ขับรถไม่ชำนาญ / ไม่เป็น
ขับรถไม่เปิดไฟ / ไม่ใช้แสงสว่างตามกำหนด
ขับรถไม่เปิดไฟ/ไม่ใช้แสงสว่างตามกำหนด
ข้ามถนนโดยมีรถจอดหรือวัตถุข้างทางบดบังผู้ขับขี่
คน/รถ/สัตว์ตัดหน้ากระชั้นชิด
ความประมาท/เร่งรีบ (วิ่งตัดหน้า)
ความเมื่อยล้า
ถนนชำรุด
ถนนลื่น
ถนนแคบ
ทางโค้งอันตราย
ทำงานบนถนน
นั่งบุคคลขับรถย้อนทิศทางจราจร
บรรทุกสูงเกินกำหนด
บรรทุกเกินอัตรา
ปัญหาทางสายตา
ป้ายจราจรถูกบดบัง
ผิวถนนสภาพแย่หรือชำรุด
ผู้ขับขี่ไม่เห็นเสาไฟส่องสว่าง
ฝาตู้เก็บของด้านข้างเปิด
ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมแยก
ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร
พวงมาลัยชำรุด
มีกองวัสดุ/สิ่งกีดขวาง
มีการตัดหน้าระยะกระชั้นชิด
มีคราบสะสมบนผิวถนน เช่น โคลน น้ำมัน
มีสิ่งกีดขวางบนทางหลวง (วัสดุหรือสัตว์)
มีสิ่งบดบังการมองเห็น
มีสิ่งรบกวนภายนอก เช่น ป้ายจราจรมีสีที่สว่างเกินไป
มีสิ่งรบกวนภายนอกรถ
มีสิ่งรบกวนภายในรถ
ยางรถยนต์ชำรุด
ยางเสื่อมสภาพ/ยางแตก
ยานพาหนะเคลื่อนที่ช้า
รถมีความสูงเกินกำหนด
รถเสียไม่แสดงเครื่องหมายหรือสัญญาณไฟที่กำหนด
ระบบบังขับเลี้ยวชำรุด
ระบบบังคับเลี้ยวขัดข้อง
ระบบสัญญาณไฟจราจรขัดข้อง
ระบบห้ามล้อขัดข้อง/ระบบเบรกชำรุด
ระบบไฟขัดข้องในห้องเครื่อง
ระบบไฟฟ้าขัดข้อง
ระยะการมองเห็นไม่เพียงพอ
ระยะปลอดภัยข้างทางไม่เพียงพอ
ระยะมองเห็นจำกัด
ละสายตาจากการขับขี่
ลักษณะของถนน เช่น เป็นทางโค้ง, เนินเขา, ผิวทางแคบ
สัญญาณไฟจราจรชำรุด
สูญเสียการควบคุม
หยุดรถกะทันหัน
หลับใน
หางพ่วงหลุด
อาการป่วยหรือการไร้ความสามารถทางประสาทหรือร่างกาย
อื่นๆ
อุปกรณ์ยานพาหนะบกพร่อง
เข้าผิดช่อง
เครื่องยนต์ขัดข้อง
เบรกกะทันหัน
เบรคชำรุด
เปลี่ยนช่องทางกะทันหัน
เมาสุรา
แซงรถอย่างผิดกฎหมาย
แสงสว่างไม่เพียงพอ
โรคประจำตัว
ใช้สารออกฤทธิ์ต่อจิตและประสาท
ใช้โทรศัพท์ขณะขับรถ
ไฟฟ้าแสงสว่างชำรุด
ไฟส่องสว่างชำรุด
ไม่ขับรถในช่องทางเดินรถซ้ายสุดในถนนที่มี 4 ช่องทาง
ไม่คุ้นเคยกับการขับขี่ด้านซ้าย
ไม่คุ้นเคยเส้นทาง/ขับรถไม่ชำนาญ
ไม่มีป้ายจราจร
ไม่มีมูลเหตุสันนิษฐานที่เกี่ยวข้องด้านสภาพสายทาง
ไม่มีระบบสัญญาณไฟจราจร
ไม่มีเส้นแบ่งทิศทางจราจร
ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน
ไม่ให้สัญญาณชะลอ/เลี้ยว
ไม่ให้สัญญาณเข้าจอด/ออกจากที่จอด
ไม่ให้สิทธิรถที่มาก่อนผ่านทาง เช่น ทางแยก

In [23]:
accident_all["ลักษณะการเกิดเหตุ"].value_counts(dropna=False)

ลักษณะการเกิดเหตุ
พลิกคว่ำ/ตกถนนในทางตรง                                  45440
ชนท้าย                                                  34079
พลิกคว่ำ/ตกถนนในทางโค้ง                                 11045
NaN                                                      6202
ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง)                      4865
                                                        ...
อื่นๆ (เสียหลักรื่่นไถลเข้ามาในช่องทางเดินรถตรงข้าม)        1
อื่นๆ (เสียหลักขับลงข้างทาง)                                1
อื่นๆ (ชนทางเท้า)                                           1
อื่นๆ (กระโปรงเข้าซี่ล้อรถจักรยานยนต์)                      1
อื่นๆ (รถชนคอสะพาน)                                         1
Name: count, Length: 153, dtype: int64

In [24]:
accident_all['วันที่เกิดเหตุ'] = pd.to_datetime(
    accident_all['วันที่เกิดเหตุ'], 
    format='mixed', 
    errors='coerce'
)

In [25]:
accident_all['เดือน'] = accident_all['วันที่เกิดเหตุ'].dt.month

In [26]:
thai_days = {
    "Monday": "จันทร์", "Tuesday": "อังคาร", "Wednesday": "พุธ",
    "Thursday": "พฤหัสบดี", "Friday": "ศุกร์", "Saturday": "เสาร์", "Sunday": "อาทิตย์"
}
accident_all['วันในสัปดาห์'] = accident_all['วันที่เกิดเหตุ'].dt.day_name().map(thai_days)

In [27]:
try:
    accident_all['ชั่วโมง'] = pd.to_datetime(accident_all['เวลา'].astype(str), errors='coerce').dt.hour
except:
    accident_all['ชั่วโมง'] = accident_all['เวลา'].astype(str).str.extract(r'(\d+)')[0]
    accident_all['ชั่วโมง'] = pd.to_numeric(accident_all['ชั่วโมง'], errors='coerce')

C:\Users\Asus\AppData\Local\Temp\ipykernel_26100\1806490734.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  accident_all['ชั่วโมง'] = pd.to_datetime(accident_all['เวลา'].astype(str), errors='coerce').dt.hour

In [28]:
print("เช็กจำนวนค่าว่างหลังแก้ไข:")
print(accident_all[['วันที่เกิดเหตุ', 'เดือน', 'วันในสัปดาห์', 'ชั่วโมง']].isnull().sum())

เช็กจำนวนค่าว่างหลังแก้ไข:
วันที่เกิดเหตุ        0
เดือน                 0
วันในสัปดาห์          0
ชั่วโมง           23952
dtype: int64

In [29]:
accident_all.head()

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,ACC_CODE,หน่วยงาน,สายทางหน่วยงาน,รหัสสายทาง,สายทาง,...,รถอีแต๋น,รถอื่นๆ,คนเดินเท้า,ผู้เสียชีวิต,ผู้บาดเจ็บสาหัส,ผู้บาดเจ็บเล็กน้อย,รวมจำนวนผู้บาดเจ็บ,เดือน,วันในสัปดาห์,ชั่วโมง
0,2021,2021-01-01,0:00,6/2/2021,9:04,4172437,กรมทางหลวง,ทางหลวง,2044,ร้อยเอ็ด - หนองดง,...,0,0,0,0,0,2,2,1,ศุกร์,0.0
1,2021,2021-01-01,0:02,1/2/2021,6:31,2918300,กรมทางหลวงชนบท,ทางหลวงชนบท,สน.3054,แยกทางหลวงหมายเลข 223 (กม.ที่ 11+000) - บ้านด่...,...,0,0,0,0,0,1,1,1,ศุกร์,0.0
2,2021,2021-01-01,0:05,1/2/2021,6:28,2918203,กรมทางหลวงชนบท,ทางหลวงชนบท,นพ.3015,แยกทางหลวงหมายเลข 212 (กม.ที่ 70+535) - บ้านบา...,...,0,0,0,0,0,1,1,1,ศุกร์,0.0
3,2021,2021-01-01,0:05,1/1/2021,10:16,3812049,กรมทางหลวง,ทางหลวง,4169,ทางรอบเกาะสมุย,...,0,0,0,0,0,5,5,1,ศุกร์,0.0
4,2021,2021-01-01,0:05,1/4/2021,9:40,3812534,กรมทางหลวง,ทางหลวง,1143,น้ำคลาด - ปางหมิ่น,...,0,0,0,1,2,0,2,1,ศุกร์,0.0

In [30]:
len(accident_all)

112136

In [31]:
accident_all['LATITUDE'] = pd.to_numeric(accident_all['LATITUDE'], errors='coerce')
accident_all['LONGITUDE'] = pd.to_numeric(accident_all['LONGITUDE'], errors='coerce')

In [32]:
valid_lat = (accident_all['LATITUDE'] >= 5.0) & (accident_all['LATITUDE'] <= 21.0)
valid_long = (accident_all['LONGITUDE'] >= 97.0) & (accident_all['LONGITUDE'] <= 106.0)

In [33]:
#การกรองช่วง Lat 5.0 - 21.0 และ Long 97.0 - 106.0 เป็นวิธีมาตรฐานในงาน Data Science เพื่อไม่ให้หมุดเบี้ยวเวลาปักบน Interactive Map

In [34]:
accident_all = accident_all[valid_lat & valid_long].copy()

In [35]:
len(accident_all)

111409

In [36]:
numeric_cols = [
    'รถจักรยานยนต์', 'รถสามล้อเครื่อง', 'รถยนต์นั่งส่วนบุคคล', 'รถตู้',
    'รถปิคอัพโดยสาร', 'รถโดยสารมากกว่า4ล้อ', 'รถปิคอัพบรรทุก4ล้อ', 
    'รถบรรทุก6ล้อ', 'รถบรรทุกไม่เกิน10ล้อ', 'รถบรรทุกมากกว่า10ล้อ', 
    'รถอีแต๋น', 'รถอื่นๆ', 'คนเดินเท้า', 
    'ผู้เสียชีวิต', 'ผู้บาดเจ็บสาหัส', 'ผู้บาดเจ็บเล็กน้อย', 'รวมจำนวนผู้บาดเจ็บ'
]

#แทนที่ค่าว่าง (NaN) ด้วย 0 และแปลงเป็น integer
for col in numeric_cols:
    if col in accident_all.columns:
        accident_all[col] = accident_all[col].fillna(0).astype(int)

print("จำนวน Missing Values ในคอลัมน์ตัวเลข:")
print(accident_all[numeric_cols].isnull().sum())

จำนวน Missing Values ในคอลัมน์ตัวเลข:
รถจักรยานยนต์           0
รถสามล้อเครื่อง         0
รถยนต์นั่งส่วนบุคคล     0
รถตู้                   0
รถปิคอัพโดยสาร          0
รถโดยสารมากกว่า4ล้อ     0
รถปิคอัพบรรทุก4ล้อ      0
รถบรรทุก6ล้อ            0
รถบรรทุกไม่เกิน10ล้อ    0
รถบรรทุกมากกว่า10ล้อ    0
รถอีแต๋น                0
รถอื่นๆ                 0
คนเดินเท้า              0
ผู้เสียชีวิต            0
ผู้บาดเจ็บสาหัส         0
ผู้บาดเจ็บเล็กน้อย      0
รวมจำนวนผู้บาดเจ็บ      0
dtype: int64

In [40]:
text_cols = [
    'บริเวณที่เกิดเหตุ', 'มูลเหตุสันนิษฐาน', 'ลักษณะการเกิดเหตุ', 
    'สภาพอากาศ', 'จังหวัด', 'รถคันที่1', 'สายทาง'
]

for col in text_cols:
    if col in accident_all.columns:
        accident_all[col] = accident_all[col].fillna('ไม่ระบุ').astype(str).str.strip()

In [44]:
accident_all['ชั่วโมง'] = accident_all['เวลา'].astype(str).str.extract(r'(\d+)')[0]
accident_all['ชั่วโมง'] = pd.to_numeric(accident_all['ชั่วโมง'], errors='coerce')

accident_all['ชั่วโมง'] = accident_all['ชั่วโมง'].fillna(-1).astype(int)
#-1 คือการสร้าง Out-of-bound Category หรือ Sentinel Value เพื่อใช้จัดการกับ "ข้อมูลที่ไม่ทราบเวลา / ข้อมูลขยะ"

In [45]:
accident_all.isnull().sum()

ปีที่เกิดเหตุ             0
วันที่เกิดเหตุ            0
เวลา                      0
วันที่รายงาน              4
เวลาที่รายงาน             8
ACC_CODE                  0
หน่วยงาน                  0
สายทางหน่วยงาน            0
รหัสสายทาง               10
สายทาง                    0
KM                      354
จังหวัด                   0
รถคันที่1                 0
บริเวณที่เกิดเหตุ         0
มูลเหตุสันนิษฐาน          0
ลักษณะการเกิดเหตุ         0
สภาพอากาศ                 0
LATITUDE                  0
LONGITUDE                 0
รถที่เกิดเหตุ             0
รถและคนที่เกิดเหตุ        0
รถจักรยานยนต์             0
รถสามล้อเครื่อง           0
รถยนต์นั่งส่วนบุคคล       0
รถตู้                     0
รถปิคอัพโดยสาร            0
รถโดยสารมากกว่า4ล้อ       0
รถปิคอัพบรรทุก4ล้อ        0
รถบรรทุก6ล้อ              0
รถบรรทุกไม่เกิน10ล้อ      0
รถบรรทุกมากกว่า10ล้อ      0
รถอีแต๋น                  0
รถอื่นๆ                   0
คนเดินเท้า                0
ผู้เสียชีวิต              0
ผู้บาดเจ็บสาหัส           0
ผู้บาดเจ็บเล็กน้อย        0
รวมจำนวนผู้บาดเจ็บ        0
เดือน                     0
วันในสัปดาห์              0
ชั่วโมง                   0
dtype: int64

In [46]:
(accident_all['หน่วยงาน'].value_counts(dropna=False))

หน่วยงาน
กรมทางหลวง                  103903
กรมทางหลวงชนบท                6037
การทางพิเศษแห่งประเทศไทย      1469
Name: count, dtype: int64

In [47]:
(accident_all['สายทางหน่วยงาน'].value_counts(dropna=False))

สายทางหน่วยงาน
ทางหลวง        103903
ทางหลวงชนบท      6037
การทางพิเศษ      1469
Name: count, dtype: int64

In [48]:
accident_all.to_csv('accident_cleaned_2021_2025.csv', index=False, encoding='utf-8-sig')
print("บันทึกไฟล์ accident_cleaned_2021_2025.csv สำเร็จแล้ว!")

บันทึกไฟล์ accident_cleaned_2021_2025.csv สำเร็จแล้ว!