In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('accident_cleaned.csv', parse_dates=['วันที่เกิดเหตุ'])
print("จำนวนข้อมูลพร้อมใช้งาน:", len(df))
df.head(2)

จำนวนข้อมูลพร้อมใช้งาน: 111409

C:\Users\Asus\AppData\Local\Temp\ipykernel_3152\1124788500.py:1: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('accident_cleaned.csv', parse_dates=['วันที่เกิดเหตุ'])

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,ACC_CODE,หน่วยงาน,สายทางหน่วยงาน,รหัสสายทาง,สายทาง,...,รถบรรทุกไม่เกิน10ล้อ,รถบรรทุกมากกว่า10ล้อ,รถอีแต๋น,รถอื่นๆ,คนเดินเท้า,ผู้เสียชีวิต,ผู้บาดเจ็บสาหัส,ผู้บาดเจ็บเล็กน้อย,รวมจำนวนผู้บาดเจ็บ,ชั่วโมง
0,2021,2021-01-01,0:00,6/2/2021,9:04,4172437,กรมทางหลวง,ทางหลวง,2044,ร้อยเอ็ด - หนองดง,...,0,0,0,0,0,0,0,2,2,0
1,2021,2021-01-01,0:02,1/2/2021,6:31,2918300,กรมทางหลวงชนบท,ทางหลวงชนบท,สน.3054,แยกทางหลวงหมายเลข 223 (กม.ที่ 11+000) - บ้านด่...,...,0,0,0,0,0,0,0,1,1,0

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111409 entries, 0 to 111408
Data columns (total 39 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ปีที่เกิดเหตุ         111409 non-null  int64
 1   วันที่เกิดเหตุ        111409 non-null  datetime64[ns]
 2   เวลา                  111409 non-null  object
 3   วันที่รายงาน          111405 non-null  object
 4   เวลาที่รายงาน         111401 non-null  object
 5   ACC_CODE              111409 non-null  int64
 6   หน่วยงาน              111409 non-null  object
 7   สายทางหน่วยงาน        111409 non-null  object
 8   รหัสสายทาง            111399 non-null  object
 9   สายทาง                111409 non-null  object
 10  KM                    111055 non-null  float64
 11  จังหวัด               111409 non-null  object
 12  รถคันที่1             111409 non-null  object
 13  บริเวณที่เกิดเหตุ     111409 non-null  object
 14  มูลเหตุสันนิษฐาน      111409 non-null  object
 15  ลักษณะการเกิดเหตุ     111409 non-null  object
 16  สภาพอากาศ             111409 non-null  object
 17  LATITUDE              111409 non-null  float64
 18  LONGITUDE             111409 non-null  float64
 19  รถที่เกิดเหตุ         111409 non-null  int64
 20  รถและคนที่เกิดเหตุ    111409 non-null  int64
 21  รถจักรยานยนต์         111409 non-null  int64
 22  รถสามล้อเครื่อง       111409 non-null  int64
 23  รถยนต์นั่งส่วนบุคคล   111409 non-null  int64
 24  รถตู้                 111409 non-null  int64
 25  รถปิคอัพโดยสาร        111409 non-null  int64
 26  รถโดยสารมากกว่า4ล้อ   111409 non-null  int64
 27  รถปิคอัพบรรทุก4ล้อ    111409 non-null  int64
 28  รถบรรทุก6ล้อ          111409 non-null  int64
 29  รถบรรทุกไม่เกิน10ล้อ  111409 non-null  int64
 30  รถบรรทุกมากกว่า10ล้อ  111409 non-null  int64
 31  รถอีแต๋น              111409 non-null  int64
 32  รถอื่นๆ               111409 non-null  int64
 33  คนเดินเท้า            111409 non-null  int64
 34  ผู้เสียชีวิต          111409 non-null  int64
 35  ผู้บาดเจ็บสาหัส       111409 non-null  int64
 36  ผู้บาดเจ็บเล็กน้อย    111409 non-null  int64
 37  รวมจำนวนผู้บาดเจ็บ    111409 non-null  int64
 38  ชั่วโมง               111409 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(22), object(13)
memory usage: 33.1+ MB

In [12]:
df['year'] = df['วันที่เกิดเหตุ'].dt.year
df['month'] = df['วันที่เกิดเหตุ'].dt.month
df['day'] = df['วันที่เกิดเหตุ'].dt.day
df['dayofweek'] = df['วันที่เกิดเหตุ'].dt.dayofweek  # 0=จันทร์, 6=อาทิตย์
df['is_weekend'] = df['dayofweek'].isin([5, 6]).astype(int)  # 1=เสาร์-อาทิตย์, 0=จันทร์-ศุกร์

In [13]:
def get_time_period(ชั่วโมง):
    if pd.isna(ชั่วโมง):
        return 'ไม่ระบุ'
    elif 0 <= ชั่วโมง < 4:
        return 'ดึก (00:00 - 03:59)'
    elif 4 <= ชั่วโมง < 8:
        return 'เช้ามืด (04:00 - 07:59)'
    elif 8 <= ชั่วโมง < 12:
        return 'เช้า (08:00 - 11:59)'
    elif 12 <= ชั่วโมง < 16:
        return 'บ่าย (12:00 - 15:59)'
    elif 16 <= ชั่วโมง < 20:
        return 'เย็น (16:00 - 19:59)'
    else:
        return 'กลางคืน (20:00 - 23:59)'

In [14]:
df['time_period'] = df['ชั่วโมง'].apply(get_time_period)

In [15]:
df[['วันที่เกิดเหตุ', 'เวลา', 'year', 'month', 'dayofweek', 'is_weekend', 'ชั่วโมง', 'time_period']].tail()

,วันที่เกิดเหตุ,เวลา,year,month,dayofweek,is_weekend,ชั่วโมง,time_period
111404,2025-12-31,23:15,2025,12,2,0,23,กลางคืน (20:00 - 23:59)
111405,2025-12-31,23:20,2025,12,2,0,23,กลางคืน (20:00 - 23:59)
111406,2025-12-31,23:25,2025,12,2,0,23,กลางคืน (20:00 - 23:59)
111407,2025-12-31,23:30,2025,12,2,0,23,กลางคืน (20:00 - 23:59)
111408,2025-12-31,23:55,2025,12,2,0,23,กลางคืน (20:00 - 23:59)

In [17]:
df.query("year == 2024")[['วันที่เกิดเหตุ', 'เวลา', 'year', 'month', 'dayofweek', 'is_weekend', 'ชั่วโมง', 'time_period']].tail()

,วันที่เกิดเหตุ,เวลา,year,month,dayofweek,is_weekend,ชั่วโมง,time_period
87860,2024-12-31,22:50,2024,12,1,0,22,กลางคืน (20:00 - 23:59)
87861,2024-12-31,23:10,2024,12,1,0,23,กลางคืน (20:00 - 23:59)
87862,2024-12-31,23:15,2024,12,1,0,23,กลางคืน (20:00 - 23:59)
87863,2024-12-31,23:30,2024,12,1,0,23,กลางคืน (20:00 - 23:59)
87864,2024-12-31,23:30,2024,12,1,0,23,กลางคืน (20:00 - 23:59)

In [18]:
print("ชั่วโมงต่ำสุด:", df['ชั่วโมง'].min())
print("ชั่วโมงสูงสุด:", df['ชั่วโมง'].max())

invalid_hours = df[(df['ชั่วโมง'] < 0) | (df['ชั่วโมง'] > 23)]
print("จำนวนแถวที่ค่าชั่วโมงผิดปกติ:", len(invalid_hours))

ชั่วโมงต่ำสุด: 0
ชั่วโมงสูงสุด: 23
จำนวนแถวที่ค่าชั่วโมงผิดปกติ: 0

In [19]:
missing_hours = df['ชั่วโมง'].isna().sum()
print("จำนวนค่าว่างในชั่วโมง:", missing_hours)

จำนวนค่าว่างในชั่วโมง: 0

In [20]:
print(df['time_period'].value_counts(dropna=False))

time_period
บ่าย (12:00 - 15:59)       22827
เย็น (16:00 - 19:59)       22054
เช้า (08:00 - 11:59)       21165
กลางคืน (20:00 - 23:59)    16137
เช้ามืด (04:00 - 07:59)    15744
ดึก (00:00 - 03:59)        13482
Name: count, dtype: int64

In [22]:
print(df[df['year'] == 2021]['time_period'].value_counts(dropna=False))

time_period
เย็น (16:00 - 19:59)       4189
บ่าย (12:00 - 15:59)       4181
เช้า (08:00 - 11:59)       3976
กลางคืน (20:00 - 23:59)    3153
เช้ามืด (04:00 - 07:59)    2388
ดึก (00:00 - 03:59)        2110
Name: count, dtype: int64

In [21]:
print(df[df['year'] == 2024]['time_period'].value_counts(dropna=False))

time_period
บ่าย (12:00 - 15:59)       4768
เย็น (16:00 - 19:59)       4716
เช้า (08:00 - 11:59)       4259
เช้ามืด (04:00 - 07:59)    3770
กลางคืน (20:00 - 23:59)    3185
ดึก (00:00 - 03:59)        3016
Name: count, dtype: int64

In [23]:
df.isnull().sum()

ปีที่เกิดเหตุ             0
วันที่เกิดเหตุ            0
เวลา                      0
วันที่รายงาน              4
เวลาที่รายงาน             8
ACC_CODE                  0
หน่วยงาน                  0
สายทางหน่วยงาน            0
รหัสสายทาง               10
สายทาง                    0
KM                      354
จังหวัด                   0
รถคันที่1                 0
บริเวณที่เกิดเหตุ         0
มูลเหตุสันนิษฐาน          0
ลักษณะการเกิดเหตุ         0
สภาพอากาศ                 0
LATITUDE                  0
LONGITUDE                 0
รถที่เกิดเหตุ             0
รถและคนที่เกิดเหตุ        0
รถจักรยานยนต์             0
รถสามล้อเครื่อง           0
รถยนต์นั่งส่วนบุคคล       0
รถตู้                     0
รถปิคอัพโดยสาร            0
รถโดยสารมากกว่า4ล้อ       0
รถปิคอัพบรรทุก4ล้อ        0
รถบรรทุก6ล้อ              0
รถบรรทุกไม่เกิน10ล้อ      0
รถบรรทุกมากกว่า10ล้อ      0
รถอีแต๋น                  0
รถอื่นๆ                   0
คนเดินเท้า                0
ผู้เสียชีวิต              0
ผู้บาดเจ็บสาหัส           0
ผู้บาดเจ็บเล็กน้อย        0
รวมจำนวนผู้บาดเจ็บ        0
ชั่วโมง                   0
year                      0
month                     0
day                       0
dayofweek                 0
is_weekend                0
time_period               0
dtype: int64

In [24]:
def calculate_severity(row):
    if row['ผู้เสียชีวิต'] >= 1:
        return 'รุนแรงมาก (เสียชีวิต)'
    elif row['ผู้บาดเจ็บสาหัส'] >= 1:
        return 'รุนแรงปานกลาง (บาดเจ็บสาหัส)'
    else:
        return 'รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย)'

df['severity_level'] = df.apply(calculate_severity, axis=1)

In [25]:
# ดูจำนวนนับของแต่ละระดับความรุนแรง
print(df['severity_level'].value_counts())

# ดูสัดส่วนเป็นเปอร์เซ็นต์ (%)
print("\n--- สัดส่วน (%) ---")
print(df['severity_level'].value_counts(normalize=True) * 100)

severity_level
รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย)    90868
รุนแรงมาก (เสียชีวิต)                            12218
รุนแรงปานกลาง (บาดเจ็บสาหัส)                      8323
Name: count, dtype: int64

--- สัดส่วน (%) ---
severity_level
รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย)    81.562531
รุนแรงมาก (เสียชีวิต)                            10.966798
รุนแรงปานกลาง (บาดเจ็บสาหัส)                      7.470671
Name: proportion, dtype: float64

In [26]:
def check_new_year(date):
    if pd.isna(date): return 0
    return 1 if (date.month == 12 and date.day >= 29) or (date.month == 1 and date.day <= 4) else 0

def check_songkran(date):
    if pd.isna(date): return 0
    return 1 if (date.month == 4 and 11 <= date.day <= 17) else 0

df['is_new_year'] = df['วันที่เกิดเหตุ'].apply(check_new_year)
df['is_songkran'] = df['วันที่เกิดเหตุ'].apply(check_songkran)
df['is_dangerous_7days'] = ((df['is_new_year'] == 1) | (df['is_songkran'] == 1)).astype(int)

print("ปีใหม่     :", df['is_new_year'].sum(), "เคส")
print("สงกรานต์  :", df['is_songkran'].sum(), "เคส")
print("รวม 7วันอันตราย:", df['is_dangerous_7days'].sum(), "เคส")

ปีใหม่     : 7625 เคส
สงกรานต์  : 6438 เคส
รวม 7วันอันตราย: 14063 เคส

In [27]:
newyear_check = df[df['is_new_year'] == 1].groupby(df['วันที่เกิดเหตุ'].dt.year).agg(
    เคสรวม=('is_new_year', 'count'),
    จำนวนวัน=('วันที่เกิดเหตุ', lambda x: x.dt.date.nunique())
)
print(newyear_check)

songkran_check = df[df['is_songkran'] == 1].groupby(df['วันที่เกิดเหตุ'].dt.year).agg(
    เคสรวม=('is_songkran', 'count'),
    จำนวนวัน=('วันที่เกิดเหตุ', lambda x: x.dt.date.nunique())
)
print(songkran_check)

                เคสรวม  จํานวนวัน
วันที่เกิดเหตุ
2021              1286          7
2022              1606          7
2023              1813          7
2024              1510          7
2025              1410          7
                เคสรวม  จํานวนวัน
วันที่เกิดเหตุ
2021               850          7
2022              1266          7
2023              1275          7
2024              1556          7
2025              1491          7

In [28]:
df.to_csv('accident_processed_data.csv', index=False, encoding='utf-8-sig')

print("บันทึกแล้ว")

บันทึกแล้ว

In [29]:
df = df.drop_duplicates()

In [30]:
drop_list = [
    'ACC_CODE', 'สายทางหน่วยงาน',  'KM',
    'วันที่เกิดเหตุ', 'เวลา', 'วันที่รายงาน', 'เวลาที่รายงาน', 'hour',
    'ผู้เสียชีวิต', 'ผู้บาดเจ็บสาหัส', 'ผู้บาดเจ็บเล็กน้อย', 'รวมจำนวนผู้บาดเจ็บ',
    'รถและคนที่เกิดเหตุ', 'รถที่เกิดเหตุ', 'dayofweek',
    'ปีที่เกิดเหตุ', 'เดือน', 'วันในสัปดาห์', 'dangerous_label'
]

df_model = df.drop(columns=[col for col in drop_list if col in df.columns])
df_model.to_csv('for_train.csv', index=False, encoding='utf-8-sig')
print("บันทึกแล้ว")

บันทึกแล้ว

In [31]:
drop_list = [
    'ACC_CODE', 'สายทางหน่วยงาน',  'KM','รหัสสายทาง',
    'วันที่เกิดเหตุ', 'เวลา', 'วันที่รายงาน', 'เวลาที่รายงาน', 'hour',
    'รถและคนที่เกิดเหตุ', 'รถที่เกิดเหตุ', 'dayofweek',
    'ปีที่เกิดเหตุ', 'เดือน', 'วันในสัปดาห์', 'dangerous_label','รถจักรยานยนต์',
    'รถสามล้อเครื่อง',
    'รถยนต์นั่งส่วนบุคคล',
    'รถตู้',
    'รถปิคอัพโดยสาร',
    'รถโดยสารมากกว่า4ล้อ',
    'รถปิคอัพบรรทุก4ล้อ',
    'รถบรรทุก6ล้อ',
    'รถบรรทุกไม่เกิน10ล้อ',
    'รถบรรทุกมากกว่า10ล้อ',
    'รถอีแต๋น',
    'รถอื่นๆ',
    'คนเดินเท้า'
]

df2 = df.drop(columns=[col for col in drop_list if col in df.columns])
df2.to_csv('new_accident.csv', index=False, encoding='utf-8-sig')
print("บันทึกแล้ว")

บันทึกแล้ว